# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/lenovo/tab3

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/system/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.mt6735m.so:system/lib/hw/audio.primary.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.primary.mt6735m.so:system/lib64/hw/audio.primary.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiocomponentengine.so:system/lib64/libaudiocomponentengine.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiocompensationfilter.so:system/lib64/libaudiocompensationfilter.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiocustparam.so:system/lib64/libaudiocustparam.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiodcrflt.so:system/lib64/libaudiodcrflt.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiosetting.so:system/lib64/libaudiosetting.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbessound_hd_mtk.so:system/lib64/libbessound_hd_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libblisrc.so:system/lib/libblisrc.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libblisrc.so:system/lib64/libblisrc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libblisrc32.so:system/lib/libblisrc32.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libblisrc32.so:system/lib64/libblisrc32.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcvsd_mtk.so:system/lib64/libcvsd_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmsbc_mtk.so:system/lib64/libmsbc_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvram.so:system/lib/libnvram.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvram.so:system/lib64/libnvram.so \
    $(LOCAL_PATH)/proprietary/system/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    $(LOCAL_PATH)/proprietary/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio_policy.stub.so:system/lib64/hw/audio_policy.stub.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.r_submix.default.so:system/lib64/hw/audio.r_submix.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/camera.mt6735m.so:system/lib64/hw/camera.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/lib3a.so:system/lib/lib3a.so \
    $(LOCAL_PATH)/proprietary/system/lib64/lib3a.so:system/lib64/lib3a.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamalgo.so:system/lib/libcamalgo.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.campipe.so:system/lib64/libcam.campipe.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.client.so:system/lib/libcam.client.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.client.so:system/lib64/libcam.client.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.device1.so:system/lib/libcam.device1.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.device3.so:system/lib/libcam.device3.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcamdrv.so:system/lib/libcamdrv.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtkcamera_client.so:system/lib64/libmtkcamera_client.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcameracustom.so:system/lib/libcameracustom.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam_platform.so:system/lib/libcam_platform.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam_utils.so:system/lib/libcam_utils.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfeatureio.so:system/lib/libfeatureio.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    $(LOCAL_PATH)/proprietary/system/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    $(LOCAL_PATH)/proprietary/system/lib/libimageio.so:system/lib/libimageio.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libimageio.so:system/lib64/libimageio.so \
    $(LOCAL_PATH)/proprietary/system/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libJpgDecPipe.so:system/lib64/libJpgDecPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
    $(LOCAL_PATH)/proprietary/system/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libSwJpgCodec.so:system/lib64/libSwJpgCodec.so \
    $(LOCAL_PATH)/proprietary/system/bin/6620_launcher:system/bin/6620_launcher \
    $(LOCAL_PATH)/proprietary/system/bin/wmt_loader:system/bin/wmt_loader \
    $(LOCAL_PATH)/proprietary/system/bin/spm_loader:system/bin/spm_loader \
    $(LOCAL_PATH)/proprietary/system/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    $(LOCAL_PATH)/proprietary/system/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/WIFI_RAM_CODE_6735:system/etc/firmware/WIFI_RAM_CODE_6735 \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    $(LOCAL_PATH)/proprietary/system/bin/kpoc_charger:system/bin/kpoc_charger \
    $(LOCAL_PATH)/proprietary/system/lib/libshowlogo.so:system/lib/libshowlogo.so \
    $(LOCAL_PATH)/proprietary/system/bin/pq:system/bin/pq \
    $(LOCAL_PATH)/proprietary/system/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libdrmmtkutil.so:system/lib64/libdrmmtkutil.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/system/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    $(LOCAL_PATH)/proprietary/system/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    $(LOCAL_PATH)/proprietary/system/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbwc.so:system/lib/libbwc.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbwc.so:system/lib64/libbwc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libdpframework.so:system/lib/libdpframework.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libdpframework.so:system/lib64/libdpframework.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
    $(LOCAL_PATH)/proprietary/system/lib/libm4u.so:system/lib/libm4u.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libm4u.so:system/lib64/libm4u.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaal.so:system/lib/libaal.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaal.so:system/lib64/libaal.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/lights.mt6735m.so:system/lib/hw/lights.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/lights.mt6735m.so:system/lib64/hw/lights.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/app/MTKThermalManager/MTKThermalManager.apk:system/app/MTKThermalManager/MTKThermalManager.apk \
    $(LOCAL_PATH)/proprietary/system/bin/thermal:system/bin/thermal \
    $(LOCAL_PATH)/proprietary/system/bin/thermald:system/bin/thermald \
    $(LOCAL_PATH)/proprietary/system/bin/thermal_manager:system/bin/thermal_manager \
    $(LOCAL_PATH)/proprietary/system/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    $(LOCAL_PATH)/proprietary/system/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
    $(LOCAL_PATH)/proprietary/system/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
    $(LOCAL_PATH)/proprietary/system/app/LenovoTab/LenovoTab.apk:system/app/LenovoTab/LenovoTab.apk \
    $(LOCAL_PATH)/proprietary/system/app/YGPS/YGPS.apk:system/app/YGPS/YGPS.apk \
    $(LOCAL_PATH)/proprietary/system/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libMtkOmxCore.so:system/lib64/libMtkOmxCore.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxVdecEx.so:system/lib/libMtkOmxVdecEx.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaed.so:system/lib/libaed.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaed.so:system/lib64/libaed.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgui_ext.so:system/lib/libgui_ext.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgui_ext.so:system/lib64/libgui_ext.so \
    $(LOCAL_PATH)/proprietary/system/lib/libion.so:system/lib/libion.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libion.so:system/lib64/libion.so \
    $(LOCAL_PATH)/proprietary/system/lib/libion_mtk.so:system/lib/libion_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmhalImageCodec.so:system/lib64/libmhalImageCodec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmmprofile.so:system/lib/libmmprofile.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
    $(LOCAL_PATH)/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libvcodec_utility.so:system/lib64/libvcodec_utility.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmp4enc_xa.ca7.so:system/lib/libmp4enc_xa.ca7.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/memtrack.mt6735m.so:system/lib/hw/memtrack.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/memtrack.mt6735m.so:system/lib64/hw/memtrack.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/priv-app/FMRadio/FMRadio.apk:system/priv-app/FMRadio/FMRadio.apk \
    $(LOCAL_PATH)/proprietary/system/priv-app/FMRadio/lib/arm64/libfmjni.so:system/priv-app/FMRadio/lib/arm64/libfmjni.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/radio.fm.mt6735m.so:system/lib/hw/radio.fm.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/bin/msensord:system/bin/msensord \
    $(LOCAL_PATH)/proprietary/system/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    $(LOCAL_PATH)/proprietary/system/bin/nvram_daemon:system/bin/nvram_daemon \
    $(LOCAL_PATH)/proprietary/system/lib/hw/sensors.mt6735m.so:system/lib/hw/sensors.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/sensors.mt6735m.so:system/lib64/hw/sensors.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwm.so:system/lib/libhwm.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwm.so:system/lib64/libhwm.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfile_op.so:system/lib/libfile_op.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfile_op.so:system/lib64/libfile_op.so \
    $(LOCAL_PATH)/proprietary/system/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libnvram_daemon_callback.so:system/lib64/libnvram_daemon_callback.so \
    $(LOCAL_PATH)/proprietary/system/bin/wpa_supplicant:system/bin/wpa_supplicant \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    $(LOCAL_PATH)/proprietary/system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    $(LOCAL_PATH)/proprietary/system/vendor/app/Ds/Ds.apk:system/vendor/app/Ds/Ds.apk \
    $(LOCAL_PATH)/proprietary/system/vendor/app/DsUI/DsUI.apk:system/vendor/app/DsUI/DsUI.apk \
    $(LOCAL_PATH)/proprietary/system/vendor/etc/dolby/dax-default.xml:system/vendor/etc/dolby/dax-default.xml \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.a2dp.default.so:system/lib64/hw/audio.a2dp.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/libstagefright_soft_ddpdec.so:system/vendor/lib/libstagefright_soft_ddpdec.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/system/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \
    $(LOCAL_PATH)/proprietary/system/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    $(LOCAL_PATH)/proprietary/system/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
    $(LOCAL_PATH)/proprietary/system/app/MTKLogger/MTKLogger.apk:system/app/MTKLogger/MTKLogger.apk \
    $(LOCAL_PATH)/proprietary/system/bin/MtkCodecService:system/bin/MtkCodecService \
    $(LOCAL_PATH)/proprietary/system/etc/media_codecs.xml:system/etc/media_codecs.xml \
    $(LOCAL_PATH)/proprietary/system/bin/mtkrild:system/bin/mtkrild \
    $(LOCAL_PATH)/proprietary/system/bin/mtkrildmd2:system/bin/mtkrildmd2 \
    $(LOCAL_PATH)/proprietary/system/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    $(LOCAL_PATH)/proprietary/system/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libBnMtkCodec.so:system/lib64/libBnMtkCodec.so \
    $(LOCAL_PATH)/proprietary/system/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcustom_jni.so:system/lib/libcustom_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcustom_jni.so:system/lib64/libcustom_jni.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcustom_prop.so:system/lib64/libcustom_prop.so \
    $(LOCAL_PATH)/proprietary/system/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libdrmmtkwhitelist.so:system/lib64/libdrmmtkwhitelist.so \
    $(LOCAL_PATH)/proprietary/system/lib/libfeatureio.so:system/lib/libfeatureio.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    $(LOCAL_PATH)/proprietary/system/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    $(LOCAL_PATH)/proprietary/system/lib/libimageio.so:system/lib/libimageio.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libimageio.so:system/lib64/libimageio.so \
    $(LOCAL_PATH)/proprietary/system/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtcloader.so:system/lib/libmtcloader.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtkplayer.so:system/lib64/libmtkplayer.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libMtkVideoTranscoder.so:system/lib64/libMtkVideoTranscoder.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMTKAudioTimeStretch.so:system/lib/libMTKAudioTimeStretch.so \
    $(LOCAL_PATH)/proprietary/system/lib/librilmtk.so:system/lib/librilmtk.so \
    $(LOCAL_PATH)/proprietary/system/lib64/librilmtk.so:system/lib64/librilmtk.so \
    $(LOCAL_PATH)/proprietary/system/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
    $(LOCAL_PATH)/proprietary/system/lib64/librilmtkmd2.so:system/lib64/librilmtkmd2.so \
    $(LOCAL_PATH)/proprietary/system/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    $(LOCAL_PATH)/proprietary/system/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
    $(LOCAL_PATH)/proprietary/system/lib64/mtk-rilmd2.so:system/lib64/mtk-rilmd2.so \
    $(LOCAL_PATH)/proprietary/system/lib/mtk-ril.so:system/lib/mtk-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib64/mtk-ril.so:system/lib64/mtk-ril.so \
    $(LOCAL_PATH)/proprietary/system/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libvcodec_oal.so:system/lib64/libvcodec_oal.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio_policy.default.so:system/lib64/hw/audio_policy.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.primary.default.so:system/lib64/hw/audio.primary.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/audio.usb.default.so:system/lib64/hw/audio.usb.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.mt6735m.so:system/lib/hw/gralloc.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gralloc.default.so:system/lib64/hw/gralloc.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gralloc.mt6735m.so:system/lib64/hw/gralloc.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/keystore.default.so:system/lib64/hw/keystore.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/local_time.default.so:system/lib64/hw/local_time.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/power.default.so:system/lib/hw/power.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/power.default.so:system/lib64/hw/power.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/vibrator.default.so:system/lib64/hw/vibrator.default.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiopolicymanagerdefault.so:system/lib/libaudiopolicymanagerdefault.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiopolicymanagerdefault.so:system/lib64/libaudiopolicymanagerdefault.so \
    $(LOCAL_PATH)/proprietary/system/lib/libaudiopolicymanager.so:system/lib/libaudiopolicymanager.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libaudiopolicymanager.so:system/lib64/libaudiopolicymanager.so \
    $(LOCAL_PATH)/proprietary/system/lib/libhwui.so:system/lib/libhwui.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libhwui.so:system/lib64/libhwui.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/gps.mt6735m.so:system/lib/hw/gps.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/gps.mt6735m.so:system/lib64/hw/gps.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/hw/hwcomposer.mt6735m.so:system/lib/hw/hwcomposer.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib64/hw/hwcomposer.mt6735m.so:system/lib64/hw/hwcomposer.mt6735m.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam.exif.so:system/lib/libcam.exif.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    $(LOCAL_PATH)/proprietary/system/lib/libcam_utils.so:system/lib/libcam_utils.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_vt_swip.so:system/lib/libmtk_vt_swip.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_vt_utils.so:system/lib/libmtk_vt_utils.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_vt_service.so:system/lib/libmtk_vt_service.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtk_vt_wrapper.so:system/lib/libmtk_vt_wrapper.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtk_vt_wrapper.so:system/lib64/libmtk_vt_wrapper.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtksqlite3_custom.so:system/lib/libmtksqlite3_custom.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtksqlite3_custom.so:system/lib64/libmtksqlite3_custom.so \
    $(LOCAL_PATH)/proprietary/system/lib/libmtksqlite3_android.so:system/lib/libmtksqlite3_android.so \
    $(LOCAL_PATH)/proprietary/system/lib/libMtkVideoTranscoder.so:system/lib/libMtkVideoTranscoder.so \
    $(LOCAL_PATH)/proprietary/system/lib64/libmtksqlite3_android.so:system/lib64/libmtksqlite3_android.so
